# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0014_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decks',
            old_name='cards',
            new_name='deck',
        ),
        migrations.RemoveField(
            model_name='decks',
            name='account',
        ),
        migrations.AddField(
            model_name='decks',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='decks',
            name='guild',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decks',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
