# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0016_auto_20160127_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
