# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0017_decks_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='bge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='decks',
            name='date',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decks',
            name='structures',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
