# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0018_auto_20160129_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='bge',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decks',
            name='structures',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
