# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0020_auto_20160130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='postdata',
            field=models.CharField(max_length=1024),
        ),
    ]
