# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0021_auto_20160204_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='cq_zone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
