# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0023_auto_20160216_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='bge',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decks',
            name='cq_zone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decks',
            name='enemy_structures',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decks',
            name='friendly_structures',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
