# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0024_auto_20160216_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='cq_zone',
        ),
        migrations.AlterField(
            model_name='decks',
            name='deck',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
