# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0025_auto_20160226_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='canvas',
            field=models.URLField(max_length=1024),
        ),
    ]
