# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0030_auto_20160301_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='bge',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
