# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0031_auto_20160301_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enemy', models.CharField(max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
