# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0032_warstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decks',
            name='enemy_structures',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='decks',
            name='friendly_structures',
            field=models.CharField(max_length=128),
        ),
    ]
