# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0035_auto_20160310_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedisite.GameAccount'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
