# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0037_benchmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarks',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedisite.Decks'),
        ),
    ]
