# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedisite', '0038_auto_20160312_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmarks',
            old_name='account',
            new_name='deck',
        ),
    ]
